export const CHAT_BACKEND_URL = "http://localhost:8000"
export const CHAT_BACKEND_ROOM = "/room"
export const CHAT_BACKEND_ROOMS = "/rooms"
export const CHAT_BACKEND_LEAVE = "/leave"
export const CHAT_BACKEND_SUBBED = "/subscribed"
export const CHAT_BACKEND_BY_LIST = "/roomlist"

export const USER_SERVICE_URL = "http://localhost:3000"
export const USER_SERVICE_REGISTER = "/register"
export const USER_SERVICE_LOGIN = "/login"
export const USER_SERVICE_FORGOT_PASSWORD = "/request-password-reset"
export const USER_SERVICE_CHANGE_PASSWORD = "/update-password"
export const USER_SERVICE_USER_SEARCH = "/user-search"
export const USER_SERVICE_VERIFY_RESET_TOKEN = "/verify-reset-token"

export const KW_SERVICE_URL = "http://localhost:5000"
export const KW_SERVICE_ALL_KW = "/keywords"
export const KW_SERVICE_USER = "/keywords/user"
export const KW_SERVICE_ROOM_KW = "/keywords/room"
export const KW_SERVICE_ROOMS_KW = "/keywords/rooms"
export const KW_SERVICE_RECOMMEND = "/keywords/recommendations"