export const CHAT_BACKEND_URL = "http://localhost:8000"
export const CHAT_BACKEND_ROOMS = "/rooms"
export const CHAT_BACKEND_ROOM = "/room"

export const USER_SERVICE_URL = "http://localhost:3000"
export const USER_SERVICE_REGISTER = "/register"
export const USER_SERVICE_LOGIN = "/login"
export const USER_SERVICE_FORGOT_PASSWORD = "/request-password-reset"
export const USER_SERVICE_CHANGE_PASSWORD = "/update-password"
export const USER_SERVICE_USER_SEARCH = "/user-search"
export const USER_SERVICE_VERIFY_RESET_TOKEN = "/verify-reset-token"